name: CI

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:

env:
  VERSION: 1.5.0

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Download bin
        run: |
          url="https://github.com/prometheus/node_exporter/releases/download/v${{ env.VERSION }}/node_exporter-${{ env.VERSION }}.linux-amd64.tar.gz"
          wget -O- ${url} | tar xz --strip-components=1 -C ./deb/opt/vyatta-node_exporter

      - name: Build deb
        run: |
          # adjust version in deb/CONTROL
          sed -i "s|Version:.*|Version: ${VERSION}|" ./deb/DEBIAN/control
          chmod +x deb/DEBIAN/postinst
          dpkg-deb --build --root-owner-group deb

      - name: Rename deb
        run: mv deb.deb vyatta-node-exporter_$(dpkg-deb -f deb.deb Version)_$(dpkg-deb -f deb.deb Architecture).deb

      - name: Upload deb
        uses: actions/upload-artifact@v3
        with:
          name: debian-vyatta-node_exporter
          path: "vyatta-node-exporter_*.deb"

      - uses: alexellis/upload-assets@0.4.0
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["vyatta-node-exporter_*.deb"]'
